dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
	  - sfml
	  - boost
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
  - make